### ISSUE TITLE
having issue

### ISSUE THREAD

**Issue by Ex-Communicad0** [sumeetweb/Thinki-Downloader#3]
hello,

i am getting this issue can you please tell me how to fix this?

https://i.imgur.com/3wfrq1j.png

**Comment by sumeetweb** [comment]
This problem happens when curl extension is not installed or not enabled in php.ini config file.

Download and install latest version of curl from here :
https://curl.se/windows/

For enabling php curl extension, go to installation folder of php and find the php.ini file.
Open your php.ini file and remove the ; mark from the beginning of the following line:

;extension=php_curl.dll

Try to run the script again 👍.

**Comment by Ex-Communicad0** [comment]
after i fix this got another issue 

and try tried to install php-mbstring 

and now working fine!

Thank a lot
